[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "H5HoVRo9hKERxzhUqjd3T8fJHNddcM6MBuggKe4d3Ex8"

[registry]
url = "[https://api.apr.dev](https://api.apr.dev/)"

[provider]
cluster = "devnet"
wallet = "/Users/toshi/.config/solana/id.json" # YOUR_USERNAMEは自分のPCのユーザー名に置き換えてください

[scripts]
test = "node tests/myepicproject.js"